# Generated by Django 4.0.4 on 2022-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220510_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Gestion'), ('SALES', 'Vente'), ('SUPPORT', 'Support'), ('NA', 'Inconnu')], max_length=32),
        ),
    ]
