# Generated by Django 4.0.4 on 2022-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_alter_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('OPENED', 'opened'), ('CLOSED', 'closed'), ('INCOMING', 'incoming')], default='OPENED', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
