# Generated by Django 4.0.4 on 2022-05-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_event_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
    ]
